apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - whoami/app.yaml
  - whoami/http-scale.yaml
  - whoami/ingress.yaml
  - metallb/ip-pool.yaml
  - metallb/l2-advertisement.yaml
