apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-app-service-account
  namespace: default
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-app-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: web-app-service-account
  namespace: default
roleRef:
  kind: Role
  name: get-pod-role
  apiGroup: rbac.authorization.k8s.io

