spin_manifest_version = 2

[application]
name = "app-whoami"
version = "0.1.0"
authors = ["Nils Ponsard <nilsponsad@gmail.com>"]
description = ""

[variables]
pod_name = { default = "unknown" }
pod_namespace = { default = "unknown" }
pod_uid = { default = "unknown" }
pod_ip = { default = "unknown" }
node_name = { default = "unknown" }
host_ip = { default = "unknown" }


[[trigger.http]]
route = "/..."
component = "app-whoami"

[component.app-whoami.variables]
pod_name = "{{ pod_name }}"
pod_namespace = "{{ pod_namespace }}"
pod_uid = "{{ pod_uid }}"
pod_ip = "{{ pod_ip }}"
node_name = "{{ node_name }}"
host_ip = "{{ host_ip }}"

[component.app-whoami]
source = "target/wasm32-wasi/release/app_whoami.wasm"

allowed_outbound_hosts = []
[component.app-whoami.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
