apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: http-scaling
  namespace: default

spec:
  hosts:
    - "whoami.example.com"
  replicas:
    min: 1
    max: 10
  scaleTargetRef:
    deployment: whoami-app
    service: whoami-app
    port: 80
