apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: http-scaling
  namespace: default
spec:
  hosts:
    - whoami.example.com
  replicas:
    min: 0
    max: 10
  scaleTargetRef:
    kind: Deployment
    name: whoami-app
    service: whoami-app
    port: 80
  scaledownPeriod: 1
  scalingMetric:
    requestRate:
      granularity: 1s                
      targetValue: 10 # default 100
      window: 10s # default: 1m
