apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaling
  namespace: default
spec:
  scaleTargetRef:
    name: whoami-app
  minReplicaCount: 1
  maxReplicaCount: 50
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"